### ISSUE TITLE
use standard DBAPI conventions

### ISSUE THREAD

**Issue by hunterowens** [CityofSantaMonica/mds-provider#33]
currently, MDS provider uses `ProviderDataLoader(user, password, dbname, host, port)` to connect to databases (Postgres?) 

the more pythonic way to do this would be to accept engine configuration strings (for example, here is how [SQLAlchemy](https://docs.sqlalchemy.org/en/latest/core/engines.html) does it. low priority issue of course.

**Comment by thekaveman** [comment]
You're right. It [passes those args into `sqlalchemy.create_engine`](https://github.com/CityofSantaMonica/mds-provider/blob/master/mds/db/load.py#L16), no reason to be more Pythonic and accept other inputs to the `__init__`
