### ISSUE TITLE
contribute to dev or master?

### ISSUE THREAD

**Issue by niketanpatel** [CityofSantaMonica/mds-provider#59]
are we supposed to make contributions to dev or master?

the mds-provider-services uses the master branch for pip installing the libraries. should we PR dev into master, and make master the default branch for this repo?

**Comment by thekaveman** [comment]
Right, `master` is the stable reference for e.g. pip installing.

#55 is an example of an open PR for `dev` -> `master`, representing the next release `0.2.0`. PRs should generally target `dev`, unless it is an urgent break-fix.

`dev` will stay as the default to help ensure correct PR targeting the first time.

**Comment by thekaveman** [comment]
I think this was answered above. Let me know if not...
